# Site settings
title: jack campbell - audio programmer
email: jackcampbell@acm.org
description: > # this means to ignore newlines until "baseurl:"
  A simple, whitespace, helvetica based portfolio theme.
baseurl:  # the subpath of your site, e.g. /blog/
url:  # the base hostname & protocol for your site
twitter_username: jc_bloops
github_username:  jcampbellcodes

# Build settings
markdown: kramdown

highlighter: rouge

# Pagination
paginate: 15
paginate_path: "/blog/page:num/"

collections:
  sound_design:
    output: true
    permalink: /sound_design/:path/

